apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: bushnevyuri/jmeter-master
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 15; done;" ]
        volumeMounts:
          - name: test-volume
            mountPath: /run_test
            subPath: "run_test"
        ports:
        - containerPort: 60000
      volumes:
      - name: test-volume 
        configMap:
         name: jmeter-load-test
